<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN-HBharish-1" ignored="0" name="Login Test_2" tests="1" failures="1" timestamp="25 Apr 2017 06:21:10 GMT" time="35.478" errors="0">
  <testcase name="doLogin_2" time="34.606" classname="com.unisys.pom.testcases.LoginTest_2">
    <failure type="java.lang.AssertionError" message="User NOT Logged in">
      <![CDATA[java.lang.AssertionError: User NOT Logged in
	at com.unisys.pom.testcases.base.BaseTest.reportFailure(BaseTest.java:92)
	at com.unisys.pom.testcases.LoginTest_2.doLogin_2(LoginTest_2.java:46)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- doLogin_2 -->
</testsuite> <!-- Login Test_2 -->
